README.md
wiki/README.md

As discussed on our documentation meeting 2014-11-20. Added some hopefully uncontroversial things we did not explicitly decide then.

Wiki conventions

---

styleguide/css/README.md

I think we need one: I've heard grumblings more than once about our CSS structure and rules not being explicit, and that it changes from project to project.
As the styleguide states, it's aspirational. We don't have a single project that is exactly like this, but these are my thoughts on what we should aim for.
Please give feedback!

Flesh out CSS/Sass styleguide

---

definition_of_done/README.md

DoD: check print preview when called for

---

styleguide/README.md

Add a special case why you should lock down a Gemfile

---

styleguide/README.md

This will speed up the pull requests a bit. We can tweak the number of weeks if needed.
What do you guys think?

Add rule to styleguide voting

---

styleguide/README.md

See discussion here:
https://github.com/barsoom/auctionet/commit/a5cfbe6e028f6b4252cd810cab6893ea5517ea0d#commitcomment-9044301
This adds a rule that make SENSE.
(Not Kim since she won't be back within 2 weeks.)

ruby class layout style

---

styleguide/README.md

(Not Kim since she won't be back within 2 weeks.)

Use %w[] and friends with square brackets

---

styleguide/README.md

Styleguide, JS: 'if ()', not 'if()'

---

styleguide/README.md

Styleguide: Use %r{} with slashes

---

styleguide/README.md

Simplify consensus model.

---

styleguide/README.md

Styleguide: blank line below guard statements

---

styleguide/README.md

Add private class method to the class layout

---

styleguide/css/README.md

The actual text change isn't very strongly phrased: the purpose of this pull request is mostly to have somewhere to discuss what we want to do about legacy CSS. The exact phrasing in the README isn't that important, maybe.
So: should we keep piling on anything-goes CSS in old projects, e.g. Auctionet admin and Bookie? Or should we try to write any new CSS in the new style (BEM etc)?

Don't "broken window" old projects

---

styleguide/README.md

Styleguide: Document ID for anchor

---

styleguide/README.md

Styleguide: _html and _markdown i18n suffixes

---

how_we_work/README.md

Add meetings and time-stuff to devbook

---

styleguide/README.md

Less gemfile comments

---

styleguide/README.md

Prefer 'alias_method' to 'alias'

---

styleguide/README.md

As discussed:
https://github.com/barsoom/auctionet/commit/7868cc2f0aa3b334600a6e695c601d585d254ea5#diff-0c9bedcba94ebdef9e632fc80b26eed7

Styleguide: rule of thumb for 'NOTE' comments

---

styleguide/css/README.md

Instead of a checklist in the PR message, let's try GitHub's new "Reviewers" functionality – I think maybe you can approve the PR somewhere in the UI. The last person to approve (if everyone does), please merge.

CSS: More in "Don't style by ID"

---

styleguide/README.md

Prefer 'to have_received' over 'to receive'

---

how_we_work/README.md

We've had a few situations where someone made a well-intentioned joke about blame and the receiving party noticed these ill effects.

How we work: Don't joke about blame

---

styleguide/README.md

The last reviewer to approve this (if we all approve) can please merge and close the PR.
Based on this discussion: https://github.com/barsoom/auctionet/commit/59b1d684c79075b1784c31fa1c8df7fa05eef279#r25812409

Styleguide: Explicit branches

---

how_we_work/README.md

It was mentioned during a retro. I thought this was the right place for this. Feel free to change the wording if you figure out a neater way to convey this idea.

Adding a bit about spreading knowledge.

---

deploy_without_downtime/README.md

This PR fixes a one-word typo.

Typo fix: hsa -> has

---

deploy_without_downtime/README.md

I just used this documentation to follow a procedure, and noted an update.
Anything I missed?

Database: Use current methods to ignore columns

---

styleguide/README.md
styleguide/javascript/README.md

We are interested in the JS styleguide. Re-opening PR.
This reverts commit bf882c567c16c6844e2b121fcf4b183928f7b5c3, reintroducing the document @aalin began. Thanks! 🌟 
If there are section where we want other language, please comment.
Ciao!

JS Styleguide

---

styleguide/README.md

Please rewrite and reformat as you want, as long as we get the message through! :)
Could be good with some explanations that show what the actual command would be with different inputs. idk. Do whatever you want with it.

Don't use interpolations with Kernel.system, encourage use of ShellWords
